title: CS50
description: I don't know yet
template:
  repo: cs50-template
  name: cs50
  description: my labs with CS50
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
